// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_layout from "./routes/_layout.tsx";
import * as $achievements from "./routes/achievements.tsx";
import * as $add_milestone from "./routes/add-milestone.tsx";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_register from "./routes/api/auth/register.ts";
import * as $api_db_index from "./routes/api/db/index.ts";
import * as $api_index from "./routes/api/index.ts";
import * as $api_milestones_index from "./routes/api/milestones/index.ts";
import * as $community from "./routes/community.tsx";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $goals from "./routes/goals.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $register from "./routes/register.tsx";
import * as $AuthContext from "./islands/AuthContext.tsx";
import * as $FeedTabs from "./islands/FeedTabs.tsx";
import * as $HomeRedirect from "./islands/HomeRedirect.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $LoginRedirect from "./islands/LoginRedirect.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import * as $ProtectedRoute from "./islands/ProtectedRoute.tsx";
import * as $RegisterForm from "./islands/RegisterForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_layout.tsx": $_layout,
    "./routes/achievements.tsx": $achievements,
    "./routes/add-milestone.tsx": $add_milestone,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/register.ts": $api_auth_register,
    "./routes/api/db/index.ts": $api_db_index,
    "./routes/api/index.ts": $api_index,
    "./routes/api/milestones/index.ts": $api_milestones_index,
    "./routes/community.tsx": $community,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/goals.tsx": $goals,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/register.tsx": $register,
  },
  islands: {
    "./islands/AuthContext.tsx": $AuthContext,
    "./islands/FeedTabs.tsx": $FeedTabs,
    "./islands/HomeRedirect.tsx": $HomeRedirect,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/LoginRedirect.tsx": $LoginRedirect,
    "./islands/Navbar.tsx": $Navbar,
    "./islands/ProtectedRoute.tsx": $ProtectedRoute,
    "./islands/RegisterForm.tsx": $RegisterForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
